name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt  # Enables caching for SBT dependencies

      - name: Set Up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9  # Ensures the latest stable SBT version

      - name: Build and Run Tests
        shell: bash
        working-directory: /home/shopping-basket
        run: sbt -v +test
